---
title: "Writing Functions in R"
author: "Roya Safaeinili"
output: github_document
---

```{r}
library(tidyverse)
```

Today we will be learning to write our own functions in R.

```{r}
exp_growth <- function(xt,r){
  r * xt
}

simulate <- function(max_time, x0, r){
  
  x <- numeric(max_time)
  x[1] <- x0
  
  for (t in 1:(max_time - 1)){
    x[t+1] <- exp_growth(x[t],r)
  }
  
  pop_data <- data_frame(time = 1:max_time, population_size = x)
  pop_data
  
  
}

simulate(41,10,1.5)
```

```{r}
simulate(41,10,1.5) %>%
  ggplot( aes(x = time, y = population_size)) +
      geom_point() +
      xlab('Time') +
      ylab('Population Size') + 
      ggtitle('Exponential Population Growth')
```
$$x_{t+1} = r x_t \left(1-\frac{x_t}{K}\right)$$

```{r}
growth <- function(xt, r, K){
  x_t <- r * xt*(1-(xt/K))
}


simulate2 <- function(max_time, x0, r, K){
  
  x <- numeric(max_time)
  x[1] <- x0
  
  for (t in 1:(max_time - 1)){
    x[t+1] <- growth(x[t],r,K) + x[t]
  }
  
  pop_data <- data_frame(time = 1:max_time, population_size = x)
  pop_data
}

simulate2(50,10,0.2,1000) %>%
  ggplot(aes(time,population_size)) +
  geom_point() +
  xlab('Time') +
  ylab('Population Size') + 
  ggtitle('Logarithmic Population Growth')
```
```{r}
r_range <- seq(1,3,length.out = 400)

df<- simulate2(100,10,r_range[1],100) %>%
  filter(time == 100) %>%
  mutate(r = r)

for (r in r_range){
  df1 <- simulate2(300,10,r,100) %>%
    filter(time > 200) %>%
    mutate(r = r)
  
  df <- bind_rows(df, df1)
}

df %>% ggplot(aes(r,population_size)) +
  geom_point(size = 0.1)
```

